import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import {
  api,
  type AIReport,
  type Instrument,
  type NewsItem,
  type PriceSeries,
} from "../api";
import PriceChart from "../components/PriceChart";
import { useAuth } from "../auth";

const RANGES = ["1D", "1W", "1M", "3M", "1Y"] as const;

export default function InstrumentPage() {
  const { id } = useParams<{ id: string }>();
  const instrumentId = Number(id);
  const { user, refresh } = useAuth();

  const [inst, setInst] = useState<Instrument | null>(null);
  const [range, setRange] = useState<(typeof RANGES)[number]>("1M");
  const [series, setSeries] = useState<PriceSeries | null>(null);
  const [news, setNews] = useState<NewsItem[]>([]);
  const [report, setReport] = useState<AIReport | null>(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    void (async () => {
      setErr(null);
      try {
        const [i, s, n] = await Promise.all([
          api.instrument(instrumentId),
          api.prices(instrumentId, range),
          api.news(instrumentId, 14),
        ]);
        setInst(i);
        setSeries(s);
        setNews(n);
      } catch (e) {
        setErr((e as Error).message);
      }
    })();
  }, [instrumentId, range]);

  const genReport = async (mode: "short" | "long") => {
    setBusy(true);
    setErr(null);
    try {
      const r = await api.aiReport(instrumentId, mode);
      setReport(r);
    } catch (e) {
      setErr((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  const last = series?.candles.at(-1);
  const prev = series?.candles.at(-2);
  const change = last && prev ? last.close - prev.close : 0;
  const pct = last && prev ? (change / prev.close) * 100 : 0;

  return (
    <>
      {err && <div className="error">{err}</div>}
      {inst && (
        <div className="card">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div>
              <h2 style={{ margin: 0 }}>
                {inst.symbol} <span className="muted">{inst.name}</span>
              </h2>
              <div className="muted">
                {inst.sector || inst.kind} • {inst.currency} •{" "}
                <span className="pill">source: {series?.source ?? "…"}</span>
              </div>
            </div>
            {last && (
              <div style={{ textAlign: "right" }}>
                <div style={{ fontSize: 24, fontWeight: 700 }}>{last.close.toFixed(2)}</div>
                <div className={change >= 0 ? "bull" : "bear"}>
                  {change >= 0 ? "+" : ""}
                  {change.toFixed(2)} ({pct.toFixed(2)}%)
                </div>
              </div>
            )}
          </div>

          <div style={{ marginTop: 12, display: "flex", gap: 8, flexWrap: "wrap" }}>
            {RANGES.map((r) => (
              <button
                key={r}
                onClick={() => setRange(r)}
                style={{
                  opacity: r === range ? 1 : 0.6,
                }}
              >
                {r}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="card">{series && <PriceChart candles={series.candles} />}</div>

      <div className="card">
        <h3>AI report</h3>
        <div style={{ display: "flex", gap: 8 }}>
          <button disabled={busy} onClick={() => genReport("short")}>
            {busy ? "Generating…" : "Short-term report"}
          </button>
          <button disabled={busy} onClick={() => genReport("long")}>
            {busy ? "Generating…" : "Long-term report (premium)"}
          </button>
          {user?.plan !== "premium" && (
            <span className="muted" style={{ alignSelf: "center" }}>
              Long-term requires premium. <a onClick={() => refresh()} href="/billing">Upgrade</a>
            </span>
          )}
        </div>
        {report && (
          <>
            <pre style={{ marginTop: 12 }}>{report.summary}</pre>
            <div className="muted">
              {report.mocked ? "Mock output (no OPENAI_API_KEY set)" : "Generated by LLM"}
            </div>
          </>
        )}
      </div>

      <div className="card">
        <h3>News</h3>
        {news.length === 0 && <p className="muted">No recent news.</p>}
        {news.slice(0, 10).map((n, i) => (
          <div key={i} style={{ borderBottom: "1px solid var(--border)", padding: "8px 0" }}>
            <a href={n.url} target="_blank" rel="noreferrer">
              <strong>{n.title}</strong>
            </a>
            <div className="muted">
              {n.source} • {new Date(n.published_at).toLocaleString()}
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
